CREATE TABLE cars (make varchar(20));

SELECT * FROM cars;

INSERT INTO cars VALUES('HONDA');
INSERT INTO cars VALUES('HONDA');
INSERT INTO cars VALUES('HONDA');
INSERT INTO cars VALUES('TOYOTA');
INSERT INTO cars VALUES('TOYOTA');
INSERT INTO cars VALUES('NISSAN');

SELECT COUNT(*) FROM cars;

SELECT COUNT(*),  make
FROM cars
GROUP BY make;

INSERT INTO cars VALUES(NULL);
INSERT INTO cars VALUES(NULL);
INSERT INTO cars VALUES(NULL);
INSERT INTO cars VALUES(NULL);

SELECT COUNT(*),make
FROM cars
GROUP BY make;